### ISSUE TITLE
How to get `code` with `OAuthAuthenticator`?

### ISSUE THREAD

**Issue by kyanny** [jubilee-works/timetree-sdk-js#664]
Hi, I am trying to use `OAuthAuthenticator`.

I followed [Get OAuth Access Token](https://github.com/jubilee-works/timetree-sdk-js/tree/master/web-api#get-oauth-access-token) instruction, but I could not get `code`.

> // -> TimeTree redirects to URI specified redirect_uri with code parameter. The code parameter expires in 10 minutes

I am not sure how to get the redirected URL, too.

I ran this `index.js` for testing.

```js
import { OAuthAuthenticator } from "@timetreeapp/web-api";

const authenticator = new OAuthAuthenticator();

const res = await authenticator.authorize({
  clientId: process.env.CLIENT_ID,
  redirectUri: process.env.REDIRECT_URI,
  // state: "<your-state>",
});
console.log(res);
```

I got the following result.

```
$ CLIENT_ID=XXXXXXXX REDIRECT_URI=http://localhost:9292 node .
{ status: 200, statusText: 'OK' }
```

Could you elaborate on a concrete usage of `OAuthAuthenticator`?

**Comment by fujikky** [comment]
Hi @kyanny 

Sorry, we found a problem with the `authenticator.authorize()` function in the SDK.
Since the authorize endpoint of OAuth is accessed by the end user from a browser, please build the URL as follows and access it with a browser. ([See docs](https://developers.timetreeapp.com/ja/docs/api/oauth-app#authorization-flow))

```
GET https://timetreeapp.com/oauth/authorize?client_id={client_id}&response_type=code&state={csrf_token}
```

After authentication by the browser, the `code` will be passed to the redirect URL.
We will try to fix the SDK issue soon.

Alternatively, we recommend using a package like `client-oauth2`.
Sample Code:

```js
import ClientOAuth2 from "client-oauth2";

const oauth2 = new ClientOAuth2({
  clientId: "<your-client-id>",
  clientSecret: "<your-client-secret>",
  redirectUri: "<redirect-url>",
  authorizationUri: "https://timetreeapp.com/oauth/authorize",
  accessTokenUri: "https://timetreeapp.com/oauth/token",
  state: "test",
});

console.log(oauth2.code.getUri()); // https://timetreeapp.com/oauth/authorize?client_id=xxx....
// Open the above URL in your browser.
```

**Comment by kyanny** [comment]
@fujikky thank you for your quick response!
I will try the alternative solutions you've suggested.
